server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    exchenge:
      producer: ex.producer.aula-spring
    routing-key:
      producer: rk.producer.aula-spring
    dead-letter:
      producer: dl.producer.aula-spring
    parking-lot:
      producer: pl.producer.aula-spring